### ISSUE TITLE
Add /about page

### ISSUE THREAD

**Issue by bitemyapp** [lorepub/moot#6]
Add a stubbed about page explaining `moot`, you don't have to try to write final copy for this.

**Comment by SolviQorda** [comment]
I'm super interested in contributing to this project - completely new to yesod though. @jezen does your offer still stand?

**Comment by jezen** [comment]
@SolviQorda Yes, that offer still stands.

Please first get this project working locally on your machine; you can use the instructions in the README. Then you can email me at `jezen [at] jezenthomas.com` and book a time with me any evening this week except Friday. I'm on EEST currently.

**Comment by SolviQorda** [comment]
Amazing - thank you!

**Comment by SolviQorda** [comment]
I've had a shot at this - still trying to get the project to work locally.

I can get the backend showing on localhost, but I have to comment out some lines that throw errors for variables out of scope in order to do so.
The frontend, however, throws an ELIFECYCLE error in npm.

I can add these errors as an issue, if it's useful?

Otherwise I'll keep trying to figure it out myself for the time being.

**Comment by jezen** [comment]
@SolviQorda If it's not too much trouble, it probably would be useful to document difficulties you have in GH Issues. If you hit a wall, we can pair on it and I might be able to help. I'd like any challenges to be documented as far as possible, so other people can also benefit.

**Comment by SolviQorda** [comment]
Hey, hope it was OK to submit my attempt as a PR - thought I should give it an attempt as the app appeared to be running on my machine!

**Comment by joelmccracken** [comment]
Looks like this could be closed!
